[workspace]
members = ["cli", "rust"]
default-members = ["cli"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/s2-streamstore/tailsurf"
rust-version = "1.95"
version = "0.12.2"

[workspace.dependencies]
axoupdater = { version = "0.10.2", default-features = false, features = ["github_releases"] }
base64 = "0.23.1"
bytes = "1.12.1"
clap = "4.6.6"
eyre = "0.6.14"
futures-util = "0.3.34"
humantime = "2.4.0"
memchr = "2.8.3"
rand = "0.10.2"
reqwest = "0.13.4"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = "1.0.229"
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = "1.53.1"
tokio-tungstenite = "0.30.0"
ubid = { version = "0.1.5", features = ["serde"] }
url = "2.5.8"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"

# The profile used by cargo-dist for release binaries.
[profile.dist]
inherits = "release"
lto = "thin"
